package com.the15373.dochub.pojo;
// Generated 2018-6-24 22:12:53 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.the15373.dochub.dto.Dto;
import com.the15373.dochub.dto.ExcelrecordDto;
import com.the15373.dochub.util.DateUtil;

/**
 * Excelrecord generated by hbm2java
 */
@Entity
@Table(name = "excelrecord")
public class Excelrecord implements java.io.Serializable, Dto<ExcelrecordDto> {

	private static final long serialVersionUID = 1L;
	private Long recordid;
	private Excel excel;
	private User user;
	private String record;
	private Date time;

	public Excelrecord() {
	}

	public Excelrecord(String record, Date time) {
		this.record = record;
		this.time = time;
	}

	public Excelrecord(Excel excel, User user, String record, Date time) {
		this.excel = excel;
		this.user = user;
		this.record = record;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recordid", unique = true, nullable = false)
	public Long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(Long recordid) {
		this.recordid = recordid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "excelid")
	public Excel getExcel() {
		return this.excel;
	}

	public void setExcel(Excel excel) {
		this.excel = excel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "record", nullable = false, length = 65535)
	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Override
	public ExcelrecordDto toDto() {
		ExcelrecordDto dto = new ExcelrecordDto();
		dto.setRecord(this.getRecord());
		dto.setRecordid(this.getRecordid().toString());
		dto.setTime(DateUtil.sdf.format(this.getTime()));
		return dto;
	}

}
