package com.the15373.dochub.pojo;
// Generated 2018-6-24 22:12:53 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.the15373.dochub.dto.Dto;
import com.the15373.dochub.dto.FileDto;
import com.the15373.dochub.util.DateUtil;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file")
public class File implements java.io.Serializable, Dto<FileDto> {

	private static final long serialVersionUID = 1L;
	private Long fileid;
	private Notice notice;
	private User user;
	private String filename;
	private String path;
	private String md5;
	private Date time;

	public File() {
	}

	public File(String filename, Date time) {
		this.filename = filename;
		this.time = time;
	}

	public File(Notice notice, User user, String filename, String path, Date time) {
		this.notice = notice;
		this.user = user;
		this.filename = filename;
		this.path = path;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fileid", unique = true, nullable = false)
	public Long getFileid() {
		return this.fileid;
	}

	public void setFileid(Long fileid) {
		this.fileid = fileid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noticeid")
	public Notice getNotice() {
		return this.notice;
	}

	public void setNotice(Notice notice) {
		this.notice = notice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "filename", nullable = false, length = 64)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "path", length = 65535)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "md5", nullable = false, length = 32)
	public String getMd5() {
		return md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	@Override
	public FileDto toDto() {
		FileDto dto = new FileDto();
		dto.setFileid(this.getFileid() + "");
		dto.setFilename(this.getFilename());
		dto.setTime(DateUtil.sdf.format(this.getTime()));
		dto.setUser(this.getUser().toDto());
		dto.setMd5(this.getMd5());
		return dto;
	}

}
