package com.the15373.dochub.pojo;
// Generated 2018-6-24 22:12:53 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.the15373.dochub.dto.Dto;
import com.the15373.dochub.dto.ExcelDto;
import com.the15373.dochub.util.DateUtil;

/**
 * Excel generated by hbm2java
 */
@Entity
@Table(name = "excel", catalog = "test15373")
public class Excel implements java.io.Serializable, Dto<ExcelDto> {

	private static final long serialVersionUID = 1L;
	private Long excelid;
	private User user;
	private Date starttime;
	private Date deadline;
	private String description;
	private String filename;
	private String path;
	private Set<Excelrecord> excelrecords = new HashSet<Excelrecord>(0);

	public Excel() {
	}

	public Excel(Date starttime, Date deadline, String description, String filename) {
		this.starttime = starttime;
		this.deadline = deadline;
		this.description = description;
		this.filename = filename;
	}

	public Excel(User user, Date starttime, Date deadline, String description, String filename, String path,
			Set<Excelrecord> excelrecords) {
		this.user = user;
		this.starttime = starttime;
		this.deadline = deadline;
		this.description = description;
		this.filename = filename;
		this.path = path;
		this.excelrecords = excelrecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "excelid", unique = true, nullable = false)
	public Long getExcelid() {
		return this.excelid;
	}

	public void setExcelid(Long excelid) {
		this.excelid = excelid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", nullable = false, length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deadline", nullable = false, length = 19)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "filename", nullable = false, length = 64)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "path", length = 65535)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "excel")
	public Set<Excelrecord> getExcelrecords() {
		return this.excelrecords;
	}

	public void setExcelrecords(Set<Excelrecord> excelrecords) {
		this.excelrecords = excelrecords;
	}

	@Override
	public ExcelDto toDto() {
		ExcelDto dto = new ExcelDto();
		dto.setDeadline(DateUtil.sdf.format(this.getDeadline()));
		dto.setDescription(this.getDescription());
		dto.setExcelid(this.getExcelid().toString());
		dto.setFilename(this.getFilename());
		dto.setStarttime(DateUtil.sdf.format(this.getStarttime()));
		dto.setUser(this.getUser().toDto());
		
		return dto;
	}

}
