package com.the15373.dochub.pojo;
// Generated 2018-6-24 22:12:53 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.the15373.dochub.dto.Dto;
import com.the15373.dochub.dto.UserlogDto;

/**
 * Userlog generated by hbm2java
 */
@Entity
@Table(name = "userlog", catalog = "test15373")
public class Userlog implements java.io.Serializable, Dto<UserlogDto> {

	private static final long serialVersionUID = 1L;
	private Long userlogid;
	private User user;
	private Date time;
	private String useragent;
	private String ip;

	public Userlog() {
	}

	public Userlog(Date time, String useragent) {
		this.time = time;
		this.useragent = useragent;
	}

	public Userlog(User user, Date time, String useragent, String ip) {
		this.user = user;
		this.time = time;
		this.useragent = useragent;
		this.ip = ip;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userlogid", unique = true, nullable = false)
	public Long getUserlogid() {
		return this.userlogid;
	}

	public void setUserlogid(Long userlogid) {
		this.userlogid = userlogid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "useragent", nullable = false, length = 65535)
	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

	@Column(name = "ip", length = 64)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Override
	public UserlogDto toDto() {
		// TODO Auto-generated method stub
		return null;
	}

}
