package com.the15373.dochub.pojo;
// Generated 2018-6-24 22:12:53 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.the15373.dochub.dto.Dto;
import com.the15373.dochub.dto.UserDto;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test15373")
public class User implements java.io.Serializable, Dto<UserDto> {

	private static final long serialVersionUID = 1L;
	private Long userid;
	private String account;
	private String studentnumber;
	private String name;
	private String password;
	private String school;
	private String institute;
	private String major;
	private String sex;
	private String classnumber;
	private String phonenumber;
	private String email;
	private Set<Notice> notices = new HashSet<Notice>(0);
	private Set<Excel> excels = new HashSet<Excel>(0);
	private Set<File> files = new HashSet<File>(0);
	private Set<Excelrecord> excelrecords = new HashSet<Excelrecord>(0);
	private Set<Relationship> relationships = new HashSet<Relationship>(0);
	private Set<Sharefile> sharefiles = new HashSet<Sharefile>(0);
	private Set<Userlog> userlogs = new HashSet<Userlog>(0);
	@Column(name = "sex", nullable = false, length = 1)
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public User() {
	}

	public User(String account, String studentnumber, String name, String password, String school, String institute,
			String major, String phonenumber) {
		this.account = account;
		this.studentnumber = studentnumber;
		this.name = name;
		this.password = password;
		this.school = school;
		this.institute = institute;
		this.major = major;
		this.phonenumber = phonenumber;
	}

	public User(String account, String studentnumber, String name, String password, String school, String institute,
			String major, String classnumber, String phonenumber, String email, Set<Notice> notices, Set<Excel> excels,
			Set<File> files, Set<Excelrecord> excelrecords, Set<Relationship> relationships, Set<Sharefile> sharefiles,
			Set<Userlog> userlogs) {
		this.account = account;
		this.studentnumber = studentnumber;
		this.name = name;
		this.password = password;
		this.school = school;
		this.institute = institute;
		this.major = major;
		this.classnumber = classnumber;
		this.phonenumber = phonenumber;
		this.email = email;
		this.notices = notices;
		this.excels = excels;
		this.files = files;
		this.excelrecords = excelrecords;
		this.relationships = relationships;
		this.sharefiles = sharefiles;
		this.userlogs = userlogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userid", unique = true, nullable = false)
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "account", nullable = false, length = 128)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "studentnumber", nullable = false, length = 20)
	public String getStudentnumber() {
		return this.studentnumber;
	}

	public void setStudentnumber(String studentnumber) {
		this.studentnumber = studentnumber;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 65535)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "school", nullable = false, length = 32)
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "institute", nullable = false, length = 32)
	public String getInstitute() {
		return this.institute;
	}

	public void setInstitute(String institute) {
		this.institute = institute;
	}

	@Column(name = "major", nullable = false, length = 32)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "classnumber", length = 32)
	public String getClassnumber() {
		return this.classnumber;
	}

	public void setClassnumber(String classnumber) {
		this.classnumber = classnumber;
	}

	@Column(name = "phonenumber", nullable = false, length = 13)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Notice> getNotices() {
		return this.notices;
	}

	public void setNotices(Set<Notice> notices) {
		this.notices = notices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Excel> getExcels() {
		return this.excels;
	}

	public void setExcels(Set<Excel> excels) {
		this.excels = excels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Excelrecord> getExcelrecords() {
		return this.excelrecords;
	}

	public void setExcelrecords(Set<Excelrecord> excelrecords) {
		this.excelrecords = excelrecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Relationship> getRelationships() {
		return this.relationships;
	}

	public void setRelationships(Set<Relationship> relationships) {
		this.relationships = relationships;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Sharefile> getSharefiles() {
		return this.sharefiles;
	}

	public void setSharefiles(Set<Sharefile> sharefiles) {
		this.sharefiles = sharefiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Userlog> getUserlogs() {
		return this.userlogs;
	}

	@Override
	public String toString() {
		return "User [userid=" + userid + ", account=" + account + ", studentnumber=" + studentnumber + ", name=" + name
				+ ", password=" + password + ", school=" + school + ", institute=" + institute + ", major=" + major
				+ ", classnumber=" + classnumber + ", phonenumber=" + phonenumber + ", email=" + email + "]";
	}

	public void setUserlogs(Set<Userlog> userlogs) {
		this.userlogs = userlogs;
	}

	@Override
	public UserDto toDto() {
		UserDto dto = new UserDto();
		dto.setAccount(this.getAccount());
		dto.setName(this.getName());
		dto.setEmail(this.getEmail());
		dto.setPhonenumber(this.getPhonenumber());
		dto.setMajor(this.getMajor());
		dto.setSchool(this.getSchool());
		dto.setInstitute(this.getInstitute());
		dto.setStudentnumber(this.getStudentnumber());
		dto.setSex(this.getSex());
		return dto;
	}

}
